[2024-06-11T21:55:06.122-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:55:06.137-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transform_save manual__2024-06-12T00:54:57.815947+00:00 [queued]>
[2024-06-11T21:55:06.143-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transform_save manual__2024-06-12T00:54:57.815947+00:00 [queued]>
[2024-06-11T21:55:06.144-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T21:55:06.156-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_save> on 2024-06-12 00:54:57.815947+00:00
[2024-06-11T21:55:06.158-0300] {standard_task_runner.py:63} INFO - Started process 32927 to run task
[2024-06-11T21:55:06.161-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'transform_save', 'manual__2024-06-12T00:54:57.815947+00:00', '--job-id', '1764', '--raw', '--subdir', 'DAGS_FOLDER/dag_extracao_daily.py', '--cfg-path', '/tmp/tmposwko1ig']
[2024-06-11T21:55:06.162-0300] {standard_task_runner.py:91} INFO - Job 1764: Subtask transform_save
[2024-06-11T21:55:06.191-0300] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.transform_save manual__2024-06-12T00:54:57.815947+00:00 [running]> on host Pedro-Conrado
[2024-06-11T21:55:06.269-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transform_save' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:54:57.815947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T00:54:57.815947+00:00'
[2024-06-11T21:55:06.270-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:55:06.284-0300] {logging_mixin.py:188} INFO - /home/pedro/airflow
[2024-06-11T21:55:06.302-0300] {logging_mixin.py:188} INFO - Colunas em orders: Index(['order_id', 'customer_id', 'employee_id', 'order_date', 'required_date',
       'shipped_date', 'ship_via', 'freight', 'ship_name', 'ship_address',
       'ship_city', 'ship_region', 'ship_postal_code', 'ship_country'],
      dtype='object')
[2024-06-11T21:55:06.303-0300] {logging_mixin.py:188} INFO - Colunas em products: Index(['product_id', 'product_name', 'supplier_id', 'category_id',
       'quantity_per_unit', 'unit_price', 'units_in_stock', 'units_on_order',
       'reorder_level', 'discontinued'],
      dtype='object')
[2024-06-11T21:55:06.303-0300] {logging_mixin.py:188} INFO - Colunas em customers: Index(['customer_id', 'company_name', 'contact_name', 'contact_title',
       'address', 'city', 'region', 'postal_code', 'country', 'phone', 'fax'],
      dtype='object')
[2024-06-11T21:55:06.303-0300] {logging_mixin.py:188} INFO - Colunas em order_details: Index(['order_id', 'product_id', 'unit_price', 'quantity', 'discount'], dtype='object')
[2024-06-11T21:55:06.309-0300] {logging_mixin.py:188} WARNING - /home/pedro/airflow/dags/dag_extracao_daily.py:87 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-06-11T21:55:06.312-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:55:06.313-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pedro/airflow/dags/dag_extracao_daily.py", line 128, in load_to_postgres
    save_db(df,nome)
  File "/home/pedro/airflow/dags/dag_extracao_daily.py", line 87, in save_db
    df.to_sql(nome_df, engine, if_exists='replace', index=False)
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/home/pedro/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-06-11T21:55:06.322-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=transform_save, run_id=manual__2024-06-12T00:54:57.815947+00:00, execution_date=20240612T005457, start_date=20240612T005506, end_date=20240612T005506
[2024-06-11T21:55:06.334-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1764 for task transform_save ('Engine' object has no attribute 'cursor'; 32927)
[2024-06-11T21:55:06.372-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:55:06.382-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:55:06.383-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
